[{
    "id":1,
    "icon":"",
    "title_uz":"",
    "title_ru":"",
    "title_en":"",
    "url":"/menu/id", /*for example*/
    "sub_stat":false,
    "sub_list":[],
    "search_stat" : false,
    "search_url":"/search?id=",
    "rel_menu_id":3,
    "rel_m_stat":false,
},
{
    "id":2,
    "icon":"",
    "title_uz":"",
    "title_ru":"",
    "title_en":"",
    "url":"/menu/id", /*for example*/
    "sub_stat":true,
    "sub_list":[
        {
            "id":5,
            "icon":"",
            "title_uz":"",
            "title_ru":"",
            "title_en":"",
            "url":"/menu/id", /*for example*/
            "sub_stat":false,
            "sub_list":[],
            "search_stat" : false,
            "search_url":"/search?id=",
            "rel_menu_id":3,
            "rel_m_stat":false,
        },
        {
            "id":6,
            "icon":"",
            "title_uz":"",
            "title_ru":"",
            "title_en":"",
            "url":"/menu/id", /*for example*/
            "sub_stat":false,
            "sub_list":[],
            "search_stat" : false,
            "search_url":"/search?id=",
            "rel_menu_id":3,
            "rel_m_stat":false,
        },
        {
            "id":7,
            "icon":"",
            "title_uz":"",
            "title_ru":"",
            "title_en":"",
            "url":"/menu/id", /*for example*/
            "sub_stat":false,
            "sub_list":[],
            "search_stat" : false,
            "search_url":"/search?id=",
            "rel_menu_id":3,
            "rel_m_stat":false,
        }
    ],
    "search_stat" : false,
    "search_url":null,
    "rel_menu_id":null,
    "rel_m_stat":null,
},
{
    "id":3,
    "icon":"",
    "title_uz":"",
    "title_ru":"",
    "title_en":"",
    "url":"/menu/id", /*for example*/
    "sub_stat":false,
    "sub_list":[],
    "search_stat" : true,
    "search_url":"/search?id=",
    "rel_menu_id":null,
    "rel_m_stat":null,
},
{
    "id":4,
    "icon":"",
    "title_uz":"",
    "title_ru":"",
    "title_en":"",
    "url":"/menu/id", /*for example*/
    "sub_stat":false,
    "sub_list":[],
    "search_stat" : false,
    "search_url":null,
    "rel_menu_id":null,
    "rel_m_stat":null,
}
]