# Generated by Django 2.2.12 on 2020-11-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0003_buttonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollarButtonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('collorbtn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collarbtn', to='shirtdesigner.CollarTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='CollarThreadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('collorthr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collorthr', to='shirtdesigner.CollarTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='CuffButtonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cuffbtn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuffbtn', to='shirtdesigner.CuffTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='CuffThreadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cuffthr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuffthr', to='shirtdesigner.CuffTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='PlacketButtonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('placketbtn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placketbtn', to='shirtdesigner.PlacketTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='PlacketThreadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('placketthr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placketthr', to='shirtdesigner.PlacketTypeModel')),
            ],
        ),
        migrations.DeleteModel(
            name='ButtonModel',
        ),
    ]
