# Generated by Django 2.2.2 on 2020-12-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0005_sidebarmodel_stylesidebarmodel_subsidebarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sidebarmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sidebarmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
