# Generated by Django 2.2.2 on 2020-12-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0006_auto_20201218_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricmodel',
            name='colour',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fabricmodel',
            name='composition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fabricmodel',
            name='fineness',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='fabricmodel',
            name='pattern',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fabricmodel',
            name='season',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fabricmodel',
            name='weave',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='fabricmodel',
            name='weight',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='4', max_length=2),
        ),
    ]
