# Generated by Django 2.2.2 on 2020-12-25 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0007_auto_20201225_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidebarmodel',
            name='global_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_bar', to='shirtdesigner.SideBarModel'),
        ),
    ]
