# Generated by Django 2.2.2 on 2020-12-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0008_auto_20201225_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylesidebarmodel',
            name='sub_side',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='shirtdesigner.SubSideBarModel'),
        ),
    ]
