# Generated by Django 2.2.12 on 2020-12-28 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0009_auto_20201228_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylesidebarmodel',
            name='sub_side',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='shirtdesigner.SubSideBarModel'),
        ),
    ]
