# Generated by Django 2.2.2 on 2021-01-31 14:43

from django.db import migrations, models
import django.db.models.deletion
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0011_auto_20201228_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollarStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('collar_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='SiluetObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siluet_obj', to='shirtdesigner.FabricModel')),
            ],
        ),
        migrations.CreateModel(
            name='SiluetStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('siluet_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siluet_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='SleeveObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_obj', to='shirtdesigner.FabricModel')),
            ],
        ),
        migrations.CreateModel(
            name='SleeveStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('siluet_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='backdetailsmodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='backdetailsmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bottomcutmodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='bottomcutmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='collarbuttonmodel',
            name='collorbtn',
        ),
        migrations.RemoveField(
            model_name='collarmodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='collarmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='collarthreadmodel',
            name='collorthr',
        ),
        migrations.RemoveField(
            model_name='cuffbuttonmodel',
            name='cuffbtn',
        ),
        migrations.RemoveField(
            model_name='cuffmodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='cuffmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cuffthreadmodel',
            name='cuffthr',
        ),
        migrations.RemoveField(
            model_name='placketbuttonmodel',
            name='placketbtn',
        ),
        migrations.RemoveField(
            model_name='placketmodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='placketmodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='placketthreadmodel',
            name='placketthr',
        ),
        migrations.RemoveField(
            model_name='shirtsleevemodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='shirtsleevemodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shouldermodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='shouldermodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='stylesidebarmodel',
            name='sub_side',
        ),
        migrations.DeleteModel(
            name='StyleTypeModel',
        ),
        migrations.RemoveField(
            model_name='subsidebarmodel',
            name='global_menu',
        ),
        migrations.RemoveField(
            model_name='yokemodel',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='yokemodel',
            name='type',
        ),
        migrations.DeleteModel(
            name='BackDetailsModel',
        ),
        migrations.DeleteModel(
            name='BackDetailsTypeModel',
        ),
        migrations.DeleteModel(
            name='BottomCutModel',
        ),
        migrations.DeleteModel(
            name='BottomCutTypeModel',
        ),
        migrations.DeleteModel(
            name='CollarButtonModel',
        ),
        migrations.DeleteModel(
            name='CollarModel',
        ),
        migrations.DeleteModel(
            name='CollarThreadModel',
        ),
        migrations.DeleteModel(
            name='CollarTypeModel',
        ),
        migrations.DeleteModel(
            name='CuffButtonModel',
        ),
        migrations.DeleteModel(
            name='CuffModel',
        ),
        migrations.DeleteModel(
            name='CuffThreadModel',
        ),
        migrations.DeleteModel(
            name='CuffTypeModel',
        ),
        migrations.DeleteModel(
            name='PlacketButtonModel',
        ),
        migrations.DeleteModel(
            name='PlacketModel',
        ),
        migrations.DeleteModel(
            name='PlacketThreadModel',
        ),
        migrations.DeleteModel(
            name='PlacketTypeModel',
        ),
        migrations.DeleteModel(
            name='ShirtSleeveModel',
        ),
        migrations.DeleteModel(
            name='ShoulderModel',
        ),
        migrations.DeleteModel(
            name='ShoulderTypeModel',
        ),
        migrations.DeleteModel(
            name='SleeveTypeModel',
        ),
        migrations.DeleteModel(
            name='StyleSideBarModel',
        ),
        migrations.DeleteModel(
            name='SubSideBarModel',
        ),
        migrations.DeleteModel(
            name='YokeModel',
        ),
        migrations.DeleteModel(
            name='YokeTypeModel',
        ),
        migrations.AddField(
            model_name='sleeveobjmodel',
            name='style_sleeve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_obj', to='shirtdesigner.SleeveStyleModel'),
        ),
        migrations.AddField(
            model_name='siluetobjmodel',
            name='style_siluet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siluet_obj', to='shirtdesigner.SiluetStyleModel'),
        ),
    ]
