# Generated by Django 2.2.2 on 2020-12-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0011_auto_20201228_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='related_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_style', to='shirtdesigner.SubSideBarModel'),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='related_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_menu', to='shirtdesigner.SideBarModel'),
        ),
    ]
