# Generated by Django 2.2.2 on 2021-01-31 15:03

from django.db import migrations, models
import django.db.models.deletion
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0012_auto_20210131_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuffStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('cuff_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuff_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CuffStiffnessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('cuff_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuff_stiffness', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CuffObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuff_obj', to='shirtdesigner.FabricModel')),
                ('style_cuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuff_obj', to='shirtdesigner.CuffStyleModel')),
            ],
        ),
        migrations.CreateModel(
            name='CuffBtntModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('cuff_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuff_btn', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CollarStiffnessModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('collar_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_stiffness', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CollarObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_obj', to='shirtdesigner.FabricModel')),
                ('style_collar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_obj', to='shirtdesigner.CollarStyleModel')),
            ],
        ),
        migrations.CreateModel(
            name='CollarBandHeightModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('collar_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_band_height', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='CollarBandBtntModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('collar_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_band_btn', to='shirtdesigner.SideBarModel')),
            ],
        ),
    ]
