# Generated by Django 2.2.2 on 2021-01-31 15:50

from django.db import migrations, models
import django.db.models.deletion
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0013_collarbandbtntmodel_collarbandheightmodel_collarobjmodel_collarstiffnessmodel_cuffbtntmodel_cuffobjm'),
    ]

    operations = [
        migrations.CreateModel(
            name='YokeStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('pocket_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yoke_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='YokeObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yoke_obj', to='shirtdesigner.FabricModel')),
                ('style_yoke', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yoke_obj', to='shirtdesigner.YokeStyleModel')),
            ],
        ),
        migrations.CreateModel(
            name='ShouldersStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('shoulders_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoulders_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='ShouldersObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoulders_obj', to='shirtdesigner.FabricModel')),
                ('style_shoulders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoulders_obj', to='shirtdesigner.ShouldersStyleModel')),
            ],
        ),
        migrations.CreateModel(
            name='PocketStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('pocket_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='PocketObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket_obj', to='shirtdesigner.FabricModel')),
                ('style_pocket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket_obj', to='shirtdesigner.PocketStyleModel')),
            ],
        ),
        migrations.CreateModel(
            name='PlacketStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('placket_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placket_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='PlacketObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placket_obj', to='shirtdesigner.FabricModel')),
                ('style_placket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placket_obj', to='shirtdesigner.PlacketStyleModel')),
            ],
        ),
        migrations.CreateModel(
            name='BottomStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('bottom_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='BottomObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_obj', to='shirtdesigner.FabricModel')),
                ('style_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_obj', to='shirtdesigner.BottomStyleModel')),
            ],
        ),
        migrations.CreateModel(
            name='BackStyleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(blank=True, max_length=250, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('back_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_style', to='shirtdesigner.SideBarModel')),
            ],
        ),
        migrations.CreateModel(
            name='BackObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_obj', to='shirtdesigner.FabricModel')),
                ('style_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_obj', to='shirtdesigner.BackStyleModel')),
            ],
        ),
    ]
