# Generated by Django 2.2.2 on 2020-12-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0013_auto_20201229_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StyleSideBarModel',
        ),
    ]
