# Generated by Django 2.2.2 on 2021-01-12 04:13

from django.db import migrations, models
import django.db.models.deletion
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0014_delete_stylesidebarmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleSideBarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('title_en', models.CharField(blank=True, max_length=250, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_stat', models.BooleanField(blank=True, default=False, null=True)),
                ('search_url', models.CharField(blank=True, max_length=250, null=True)),
                ('search_stat', models.BooleanField(blank=True, default=False, null=True)),
                ('related_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_style', to='shirtdesigner.SubSideBarModel')),
                ('sub_side', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_side', to='shirtdesigner.SubSideBarModel')),
            ],
        ),
    ]
