# Generated by Django 2.2.2 on 2021-01-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0016_sleevetypemodel_sleeve_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirtsleevemodel',
            name='type',
        ),
        migrations.AddField(
            model_name='shirtsleevemodel',
            name='sleeve_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeves_type', to='shirtdesigner.SubSideBarModel'),
        ),
    ]
