# Generated by Django 2.2.2 on 2021-01-12 05:22

from django.db import migrations, models
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0017_auto_20210112_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirtsleevemodel',
            name='long_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='shirtsleevemodel',
            name='short_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='shirtsleevemodel',
            name='short_with_ibbon_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
    ]
