# Generated by Django 2.2.2 on 2021-02-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0017_auto_20210209_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
