# Generated by Django 2.2.2 on 2021-02-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0018_auto_20210209_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylesidebarmodel',
            name='related_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_style', to='shirtdesigner.SubSideBarModel'),
        ),
        migrations.AddField(
            model_name='subsidebarmodel',
            name='related_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_menu', to='shirtdesigner.SideBarModel'),
        ),
        migrations.AlterField(
            model_name='stylesidebarmodel',
            name='sub_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_side', to='shirtdesigner.SubSideBarModel'),
        ),
    ]
