# Generated by Django 2.2.2 on 2021-02-24 16:42

from django.db import migrations, models
import django.db.models.deletion
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0019_auto_20210209_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuffobjmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='placketobjmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='pocketobjmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AlterField(
            model_name='siluetstylemodel',
            name='style_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Silhouette'),
        ),
        migrations.AlterField(
            model_name='subsidebarmodel',
            name='global_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_list', to='shirtdesigner.SideBarModel'),
        ),
        migrations.CreateModel(
            name='CollarObjModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location)),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_obj', to='shirtdesigner.FabricModel')),
                ('style_collar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collar_obj', to='shirtdesigner.CollarStyleModel')),
            ],
        ),
    ]
