# Generated by Django 2.2.2 on 2021-01-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0022_auto_20210112_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collarmodel',
            name='collar_img',
        ),
    ]
