# Generated by Django 2.2.2 on 2021-01-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0023_remove_collarmodel_collar_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collarmodel',
            name='back_collar_img',
        ),
    ]
