# Generated by Django 2.2.2 on 2021-01-12 10:58

from django.db import migrations, models
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0024_remove_collarmodel_back_collar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='collarmodel',
            name='typename',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='collarmodel',
            name='back_collar_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='collarmodel',
            name='collar_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
    ]
