# Generated by Django 2.2.2 on 2021-01-12 11:31

from django.db import migrations, models
import django.db.models.deletion
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0025_auto_20210112_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuffmodel',
            name='back_cuff_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='cuffmodel',
            name='cuff_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='cuffmodel',
            name='typename',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cuffmodel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cufftype', to='shirtdesigner.SubSideBarModel'),
        ),
    ]
