# Generated by Django 2.2.2 on 2021-01-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0026_auto_20210112_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collarmodel',
            name='typename',
        ),
    ]
