# Generated by Django 2.2.2 on 2021-01-12 12:00

from django.db import migrations, models
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0028_collarmodel_collarname'),
    ]

    operations = [
        migrations.AddField(
            model_name='placketmodel',
            name='placket_img',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
        migrations.AddField(
            model_name='placketmodel',
            name='placketname',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
