# Generated by Django 2.2.2 on 2021-01-19 09:56

from django.db import migrations, models
import shirtdesigner.models


class Migration(migrations.Migration):

    dependencies = [
        ('shirtdesigner', '0030_auto_20210112_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricmodel',
            name='fabric_image',
            field=models.ImageField(blank=True, null=True, upload_to=shirtdesigner.models.upload_location),
        ),
    ]
